article/urls.py
# -*- utf-8 -*-
from django.urls import path, re_path
from . import views, list_views


app_name = 'article'
urlpatterns = [
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    re_path(r'article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    re_path(r'redit_article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    path('list-article-titles/', list_views.article_titles, name='article_titles'),
    re_path(r'list-article-content/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_content,
            name='list_article_content'),
    re_path(r'list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name='author_articles'),
    path('like-article/', list_views.like_article, name='like_article'),
    path('article-tag/', views.article_tag, name='article_tag'),
    path('del-article-tag/', views.del_article_tag, name='del_article_tag')
]

blog/urls.py
# -*- utf-8 -*-
from django.urls import path, re_path
from . import views


app_name='blog'
urlpatterns = [
    re_path(r'^$', views.blog_title, name='blog_title'),
    re_path(r'(?P<article_id>\d)/$', views.blog_articles, name='blog_detail')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('image/', include('image.urls', namespace='image')),
    path('course/', include('course.urls', namespace='course'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
  # coding:utf8
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    # 文章栏目
    column = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):  # 文章标签
    author = models.ForeignKey(User, related_name='tag', on_delete=models.CASCADE)
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag


# 发布和显示文章
class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name='article', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column', on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name='article_like', blank=True)  # 点赞
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag',blank=True)

    class Meta:
        ordering = ('-updated',)
        index_together = (('id', 'slug'),)  # 建立索引

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:list_article_content', args=[self.id, self.slug])


class Comment(models.Model):  # 评论
    article = models.ForeignKey(ArticlePost, related_name='comments', on_delete=models.CASCADE)
    commentator = models.CharField(max_length=90)  # 评论员
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/forms.py
# -*- utf-8 -*-
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('commentator', 'body',)


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag',)

article/views.py
# coding:utf8
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage

from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm

import json


@login_required(login_url='/account/login/')
@csrf_exempt  # 解决CSRF问题
def article_column(request):
    if request.method == 'GET':
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', {'columns':columns, 'column_form':column_form})

    if request.method == 'POST':
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')  # 2代表已存在
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse('1')  # 1代表创建成功


@login_required(login_url='/account/login/')
@require_POST  # 只接收POST请求
@csrf_exempt
def rename_article_column(request):  # 修改栏目名称
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse('1')  # 修改成功
    except Exception:
        return HttpResponse('0')  # 修改失败


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse('1')  # 删除成功
    except Exception:
        return HttpResponse('2')  # 删除失败


@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):  # 将json格式的数据转换为列表
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse('1')  # 发布成功
            except Exception as e:
                return HttpResponse('2')  # 发布失败
        else:
            return HttpResponse('3')  # 数据错误
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        return render(request, 'article/column/article_post.html', {'article_post_form': article_post_form,
                                                                    'article_columns': article_columns,
                                                                    'article_tags': article_tags})


@login_required(login_url='/account/login')
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 2)  # 每页最多2个
    page = request.GET.get('page')  # 获得当前浏览器GET请求的参数page的值
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list  # 得到该页所有的对象列表
    except PageNotAnInteger:  # 页码数值不是整数
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:  # 数值为空
        current_page = paginator.page(paginator.num_pages)  # 返回页数
        articles = current_page.object_list
    return render(request, 'article/column/article_list.html', {'articles': articles, 'page': current_page})


@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, 'article/column/article_detail.html', {'article': article})


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')


@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == 'GET':
        article_columns = request.user.article_column.all()  # 全部栏目
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={'title': article.title})
        this_article_column = article.column
        return render(request, 'article/column/redit_article.html', {'article': article,
                                                                     'article_columns': article_columns,
                                                                     'this_article_column': this_article_column,
                                                                     'this_article_form': this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse('1')
        except:
            return HttpResponse('2')


@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
    if request.method == 'GET':
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, 'article/tag/tag_list.html', {'article_tags': article_tags,
                                                             'article_tag_form': article_tag_form})

    if request.method == 'POST':
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse('1')
            except:
                return HttpResponse('the data cannot be save.')
        else:
            return HttpResponse('sorry, the form is not valid.')


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')

templates/article/column/article_column.html
{% extends 'article/base.html' %}
{% load static %}
{% block title %}article column{% endblock %}
{% block content %}
<div>
    <p class="text-right"><button class="btn btn-primary" id="add_column" onclick="add_column()">add column</button></p>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td>
        </tr>
        {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>
                <a href="javascript:" name="edit" onclick="edit_column(this, {{ column.id }})">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a href="javascript:" name="delete" onclick="del_column(this, {{ column.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left: 20px;"></span>
                </a>
            </td>
        </tr>
        {% empty %}
        <p>还没有设置栏目，太懒了</p>
        {% endfor %}
    </table>
</div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    function add_column() {
        var index = layer.open({
            type:1,
            skin:'layui-layer-rim',
            area:['400px', '200px'],
            title:'新增栏目',
            content:'<div class="text-center" style="margin-top:20px">' +
                '<p>请输入新的栏目名称</p>{{ column_form.column }}</p></div>',
            btn:['确定', '取消'],
            yes: function (index, layero) {
                column_name = $('#id_column').val();
                $.ajax({
                    url:'{% url "article:article_column" %}',
                    type:'POST',
                    data:{"column":column_name},
                    success:function (e) {
                        if(e==='1'){
                            parent.location.reload();
                            layer.msg('good')
                        }else{
                            layer.msg('此栏目已有，请更换名称')
                        }
                    }
                })
            },
            btn2: function (index, layero) {
                layer.close(index);
            }
        })
    }

    function edit_column(the, column_id) {
        var name = $(the).parents('tr').children('td').eq(1).text();
        var index = layer.open({
            type:1,
            skin:'layui-layer-rim',
            area:['400px', '200px'],
            title:'编辑栏目',
            content:'<div class="text-center" style="margin-top:20px"><p>请编辑栏目的名称</p>' +
                '<p><input type="text" id="new_name" value="'+name+'"></p></div>',
            btn:['确定','取消'],
            yes:function (index, layero) {
                new_name = $('#new_name').val();
                $.ajax({
                    url:'{% url "article:rename_article_column" %}',
                    type:'POST',
                    data:{'column_id': column_id, 'column_name': new_name},
                    success:function (e) {
                        if(e==='1'){
                            parent.location.reload();
                            layer.msg('good');
                        }else{
                            layer.msg('新的名称没有保存，修改失败。')
                        }
                    }
                })
            }
        })
    }

    function del_column(the, column_id) {
        var name = $(the).parents('tr').children('td').eq(1).text();
       layer.open({
            type:1,
            skin:'layui-layer-rim',
            area:['400px', '200px'],
            title:'删除栏目',
            content:'<div class="text-center" style="margin-top:20px"><p>是否确定删除'+name+'栏目</p></div>',
            btn:['确定','取消'],
            yes:function () {
                $.ajax({
                    url:'{% url "article:del_article_column" %}',
                    type:'POST',
                    data:{'column_id': column_id},
                    success:function (e) {
                        if(e==='1'){
                            parent.location.reload();
                            layer.msg('has been deleted.');
                        }else{
                            layer.msg('删除失败')
                        }
                    }
                })
            }
        })
    }
</script>
{% endblock %}

templates/article/column/article_detail.html
{% extends 'article/base.html' %}
{% load static %}
{% block title %}articles list{% endblock %}
{% block content %}
<div>
    <header>
        <h1>{{ article.title }}</h1>
        <p>{{ user.username }}</p>
    </header>

    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}">
    <div id="editormd-view">
        <textarea id="append-test" style="display: none;">
            {{ article.body }}
        </textarea>
    </div>
</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}'></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>

<script type="text/javascript">
$(function(){
    editormd.markdownToHTML("editormd-view", {
        htmlDecode: "style, script, iframe",
        emoji: true,
        taskList:true,
        tex:true,
        flowChart:true,
        sequenceDiagram : true,
    });
});
</script>
{% endblock %}

templates/article/column/article_list.html
{% extends 'article/base.html' %}
{% load static %}
{% block title %}articles list{% endblock %}
{% block content %}
<div>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>标题</td>
            <td>栏目</td>
            <td>操作</td>
        </tr>
        {% for article in articles %}
        <tr id="{{ article.id }}">
            <td>{{ forloop.counter }}</td>
            <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
            <td>
                <a href="{% url 'article:redit_article' article.id %}" name="edit">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a href="javascript:" name="delete" onclick="del_article(this, {{ article.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left: 20px;"></span>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% include 'paginator.html' %}
</div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    function del_article(the, article_id) {
        var article_name = $(the).parents('tr').children('td').eq(1).text();
        layer.open({
            type: 1,
            skin: 'layui-layer-rim',
            area: ['400px', '200px'],
            title: '删除文章',
            content: '<div class="text-center" style="margin-top: 20px"><p>是否确定删除《'+article_name+'》</p></div>',
            btn: ['确定', '取消'],
            yes: function(){
                $.ajax({
                    url: '{% url "article:del_article" %}',
                    type: 'POST',
                    data: {'article_id':article_id},
                    success: function (e) {
                        if(e==='1'){
                            parent.location.reload();
                            layer.msg('has been deleted.');
                        }else {
                            layer.msg('删除失败');
                        }
                    }
                })
            }
        })
    }
</script>
{% endblock %}

templates/article/column/article_post.html
{% extends 'article/base.html' %}
{% load static %}
{% block title %}article column{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">

<div style="margin-left: 10px">
    <form action="." class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题：</span></div>
            <div class="col-md-10 text-left">{{ article_post_form.title }}</div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>栏目：</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                    <option value="{{ column.id }}">{{ column.column }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>文章标签：</span></div>
            <div class="col-md-10 text-left">
                {% for tag in article_tags %}
                <label class="checkbox-inline">
                    <input type="checkbox" class="tagcheckbox" id="{{ tag.id }}" name="article_tag"
                           value="{{ tag.tag }}">{{ tag.tag }}
                </label>
                {% empty %}
                <p>You have not type tags for articles. Please
                    <a href="{% url 'article:article_tag' %}">input your tags</a></p>
                {% endfor %}
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容：</span></div>
            <div class="col-md-10 text-left" id="editormd">
                <textarea style="display: none" id="id_body"></textarea>
            </div>
        </div>
        <div class="row" style="margin-left: 157px">
            <input type="button" class="btn btn-primary btn-lg" value="发 布" onclick="publish_article()">
        </div>
    </form>
</div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript">
    function publish_article() {
        const title = $('#id_title').val();
        const column_id = $('#which_column').val();
        const body = $('#id_body').val();
        let article_tags = [];
        $.each($("input[name='article_tag']:checked"), function () {
            article_tags.push($(this).val());
        });
        $.ajax({
            url: '{% url "article:article_post" %}',
            type: 'POST',
            data: {"title":title, "body":body, "column_id":column_id, 'tags':JSON.stringify(article_tags)}, // 变为json
            success:function (e) {
                if(e==='1'){
                    layer.msg('successful');
                    location.href = '{% url 'article:article_list' %}';
                }else if(e==='2'){
                    layer.msg('sorry');
                }else{
                    layer.msg('项目名称必须写，不能空。')
                }
            }
        })
    }

    $(function() {
        var editor = editormd("editormd", {
            width : "100%",
            height : 640,
            syncScrolling : "single",
            path : "{% static 'editor/lib/' %}"
        });
    });
</script>
{% endblock %}

templates/article/column/redit_article.html
{% extends 'article/base.html' %}
{% load static %}
{% block title %}article column{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div class="container">
    <div style="margin-left: 10px">
        <form action="." class="form-horizontal" method="post">
            {% csrf_token %}
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>标题：</span></div>
                <div class="col-md-10 text-left">{{ this_article_form.title }}</div>
            </div>
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>栏目：</span></div>
                <div class="col-md-10 text-left">
                    <select id="which_column">
                        {% for column in article_columns %}
                            {% if column == this_article_column %}
                            <option value="{{ column.id }}" selected>{{ column.column }}</option>
                            {% else %}
                            <option value="{{ column.id }}">{{ column.column }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row" style="margin-top: 10px">
                <div class="col-md-2 text-right"><span>内容：</span></div>
                <div id="editormd" class="col-md-10 text-left">
                    <textarea style="display: none;" id="id_body">
                        {{ article.body }}
                    </textarea>
                </div>
            </div>
            <div class="row">
                <input type="button" class="btn btn-primary btn-lg" value="发 布" onclick="redit_article()">
            </div>
        </form>
    </div>
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
$(function() {
    var editor = editormd("editormd", {
        width : "100%",
        height : 640,
        //syncScrolling : "single",
        path : "{% static 'editor/lib/' %}",
    });
});

function redit_article() {
    var title = $('#id_title').val();
    var column_id = $('#which_column').val();
    var body = $('#id_body').val();
    $.ajax({
        url: '{% url "article:redit_article" article.id %}',
        type: 'POST',
        data: {'title':title, 'body':body, 'column_id':column_id},
        success: function (e) {
            if(e==='1'){
                layer.msg('successful');
                location.href = "{% url 'article:article_list' %}";
            }else{
                layer.msg('sorry.')
            }
        }
    })
}
</script>
{% endblock %}