account/urls.py
# -*- utf-8 -*-
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views


app_name = 'account'
urlpatterns = [
    # path('login/', views.user_login, name='user_login'),  # 自定义的登录
    # django内置的登录
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    # 退出
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    # 注册
    path('register/', views.register, name='user_register'),
    # 修改密码
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html",
         success_url="/account/password-change-done/"),name='password_change'),
    path('password-change-done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"),
         name='password_change_done'),
    # 重置密码
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html",
                                                                 email_template_name="account/password_reset_email.html",
                                                                 success_url='/account/password-reset-done/'),
         name='password_reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html",
                                                     success_url='/account/password-reset-complete/'),
         name="password_reset_confirm"),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),
    # 个人信息
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name='edit_my_information'),
    path('my-image/',views.my_image, name='my_image')
]

article/urls.py
# -*- utf-8 -*-
from django.urls import path, re_path
from . import views, list_views


app_name = 'article'
urlpatterns = [
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    re_path(r'article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    re_path(r'redit_article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    path('list-article-titles/', list_views.article_titles, name='article_titles'),
    re_path(r'list-article-content/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_content,
            name='list_article_content'),
    re_path(r'list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name='author_articles'),
    path('like-article/', list_views.like_article, name='like_article'),
    path('article-tag/', views.article_tag, name='article_tag'),
    path('del-article-tag/', views.del_article_tag, name='del_article_tag')
]

blog/urls.py
# -*- utf-8 -*-
from django.urls import path, re_path
from . import views


app_name='blog'
urlpatterns = [
    re_path(r'^$', views.blog_title, name='blog_title'),
    re_path(r'(?P<article_id>\d)/$', views.blog_articles, name='blog_detail')
]

course/urls.py
# -*- utf-8 -*-
from django.urls import path, re_path
from django.views.generic import TemplateView
from .views import AboutView, CourseListView, ManageCourseListView, CreateCourseView, DeleteCourseView, \
    CreateLessonView, ListLessonView, DetailLessonView, StudentListLessonView

app_name = 'course'
urlpatterns = [
    # path('about/', TemplateView.as_view(template_name='course/about.html')),
    path('about/', AboutView.as_view(), name='about'),
    path('course-list/', CourseListView.as_view(), name='course_list'),
    path('manage-course/', ManageCourseListView.as_view(), name='manage_course'),
    path('create-course/', CreateCourseView.as_view(), name='create_course'),
    re_path(r'delete-course/(?P<pk>\d+)/$', DeleteCourseView.as_view(), name='delete_course'),
    path('create-lesson/', CreateLessonView.as_view(), name='create_lesson'),
    re_path(r'list-lessons/(?P<course_id>\d+)/$', ListLessonView.as_view(), name='list_lessons'),
    re_path(r'detail-lesson/(?P<lesson_id>\d+)/$', DetailLessonView.as_view(), name='detail_lesson'),
    re_path(r'lessons-list/(?P<course_id>\d+)/$', StudentListLessonView.as_view(), name='lessons_list'),
]

image/urls.py
# -*- utf-8 -*-
from django.urls import path
from . import views


app_name = 'image'
urlpatterns = [
    path('list-images/', views.list_images, name='list_images'),
    path('upload-images/', views.upload_image, name='upload_image'),
    path('del-image/', views.del_image, name='del_image'),
    path('images/', views.falls_images, name='falls_images')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('image/', include('image.urls', namespace='image')),
    path('course/', include('course.urls', namespace='course'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include 'header.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    {% block javascript %}{% endblock %}
</body>
</html>

templates/footer.html
<footer class="container">
    <hr>
    <p class="text-center">copy right www</p>
</footer>

templates/header.html
{% load static %}

<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home' %}">HOME</a></li>
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
                <li><a href="{% url 'image:falls_images' %}">美图</a></li>
                <li><a href="{% url 'course:about' %}">关于本站</a></li>
                <li><a href="{% url 'course:course_list' %}">课程</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top: 8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                                data-toggle="dropdown">{{ user.username }}<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                            <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                <li><a href="{% url 'account:user_register' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home page{% endblock %}
{% block content %}
<div class="text-center">
    <h1>WELCOME YOU</h1>
    <h3>Life is short. You need Python</h3>
    <h2>Django makes it easier to build better Web apps more quickly and with less code.</h2>
</div>
{% endblock %}

templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>